### PR TITLE
Create a container crate

### PR DESCRIPTION
**Pull request by sameo**
This PR moves the container code into its own, standalone crate.
It also fixes the `kaps` Cargo.toml package name.

### CODE REVIEW

**Review by thomasgouveia — COMMENTED** [review]
Looks good for me. Juste one question. In my PR #13, I put the `image` crate inside a `crates/` directory at the root of the project. Do you want to keep the crates at the root, or put it into a directory ? I'll adapt my PR or not in consequence.

**Comment by sameo** [comment]
> Looks good for me. Juste one question. In my PR #13, I put the `image` crate inside a `crates/` directory at the root of the project. Do you want to keep the crates at the root, or put it into a directory ? I'll adapt my PR or not in consequence.

I'd prefer to have the crates at the root of the project. This is usually how Rust projects handle it.

Also, could you please "formally" approve the PR, so that I can go ahead and merge it?

**Review by thomasgouveia — APPROVED** [review]
Ok I'll rebase my fork to have those changes when they're merged :)

**Review by MaloPolese — COMMENTED** [review]
Seems good for me, il will rebase my PR with your change 😀

**Pull request merged**
